### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PaulieScanlon** [PaulieScanlon/paulie-dev-2019#37]
I'd like to create the Dashboard using SSR as it feels kinda like an app type thing. 

- [x] Get All Reaction Accordion
- [x] Posts by Month (All Years) - Line Chart
- [x] Posts by Day (All Years) - Line Chart (refactor into single chart)
- [x] Latest Reaction
- [x]  Add polling interval for Latest Reaction
- [x] Add auto-link headings
- [ ] Upgrade to MDX v2
- [x] Add Featured Image and Twitter Link to Blog Posts Aside
- [x] Analytics Globe
   - lat/lng [not available in GA4](https://github.com/googleanalytics/ga-dev-tools/issues/962)
- [x] Add Tags Donut Chart to SSR Dashboard
- [x] Add Publishers Radar Chart to SSR Dashboard
- [ ] Add News letter signup for Queen Raae's newsletter
- [x] Add site search / [cmdk](https://cmdk.paco.me/)

**Analytics GA4**
https://developers.google.com/analytics/devguides/reporting/data/v1
- Quick Start: https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries
- JavaScript Client: https://googleapis.dev/nodejs/analytics-data/latest/index.html#installing-the-client-library
